### ISSUE TITLE
Incorrect assignment of P-CHEM properties as TOX properties (protein corona)

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#14]
After reading the original I am pretty sure that the following features of the protein corona data should be classified as physchem parameters:

https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Autot+%28ICP-AES%29/58FE7F000B07AD0C7F2001D0D031DBB09ADAD2A1/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Localized+Surface+Plasmon+Resonance+%28LSPR%29+index/2F10B953CE8756BE709BB30F84BA739905CC7C03/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Localized+Surface+Plasmon+Resonance+%28LSPR%29+index/86D26A91DAF21546BC8C39630BB8377636A98FD1/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/LSPR+peak+position+%28nm%29/304949D010ABBF94C552768F4DAC5EA52FCFA052/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Protein+density/BA330DFD2AE144D557B635662E8E7BA546B2021A/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Total+protein+%28BCA+assay%29/ABCD8CB85D6B72FE1971A0CB4335FEA90B49E9D3/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Total+surface+area+%28SAtot%29/8778865D1C682E0B8EBBEEC2AD2C6EF3D576C858/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a

IMHO only these two features are toxicity parameters:

https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Net+cell+association/62B12F0B14D8BE218BBF59144FC69360A0A8AAB4/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a
https://apps.ideaconsult.net/enanomapper/property/TOX/UNKNOWN_TOXICITY_SECTION/Log2+transformed/94D664CFE4929A0F400A5AD8CA733B52E049A688/E/3ed642f9-1b42-387a-9966-dea5b91e5f8a

**Comment by vedina** [comment]
@helma please check, these should be fixed now https://apps.ideaconsult.net/enanomapper
