### ISSUE TITLE
Search for biological model

### ISSUE THREAD

**Issue by pennym** [enanomapper/data.enanomapper.net#17]
I wonder if there would be a reason for making also biological models searchable? At this point a search on model may not be that fruitful, but later on with more data I would at least be interested in finding studies done with a certain type of cell line for example.
penny

**Comment by pennym** [comment]
Sorry, just realized that it´s already possible, but could maybe be an idea to have it under 'species'...

**Comment by vedina** [comment]
@pennym ,  yes, it is already possible , but it will be helpful if you tell what other criteria we can use for the summary statistics at the left of this [page](http://enanomapper.github.io/data.enanomapper.net/?search=cell%20viability) ? Species, cell lines, genes perhaps?

**Comment by pennym** [comment]
I think genes is so far unnecessary, that would be better as pathways, but at a later stage when there actually exists some validated nano-specific (if such exists) or -related pathways. But cell lines would be useful to me at least. And as we are moving towards animal-free tox, cell lines could even be above species. Then again ecotox will probably be interested in species...

**Comment by vedina** [comment]
Added summaries for species and cell lines, please [check](http://enanomapper.github.io/data.enanomapper.net/)  (just below the TOX section)

![image](https://cloud.githubusercontent.com/assets/211190/12839288/b016a44c-cbe0-11e5-891b-823a4bc91608.png)

**Comment by pennym** [comment]
Great!

**Comment by vedina** [comment]
thanks, closing this ticket then
