### ISSUE TITLE
Each substance (page) should have a link to this tracker

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#2]
... saying something like "Error? More info? Report here" ... that way, people can engage with us in a clear way.

Ideally, the link would be to the issues/new page, and we could explore it can automatically have some content, particularly the URI on which is being reported... that possibility would need to be explored.

**Comment by vedina** [comment]
Considering two alternatives

1) Add a generic link https://github.com/enanomapper/data.enanomapper.net/issues/
2) Add a link like below , automatically setting the title to the URI (don't know how to set the content automatically)

```
https://github.com/enanomapper/data.enanomapper.net/issues/new?title=http://example.org
```

The only problem with 2) is that if the user is not already logged in GitHub , then GitHub login window appears first.

**Comment by vedina** [comment]
Added menu item `Help/Submit an issue` since [r6895](http://sourceforge.net/p/ambit/code/6895). 

![image](https://cloud.githubusercontent.com/assets/211190/10482041/ad1c8d90-727d-11e5-835b-2a3d9cab5777.png)

**Comment by egonw** [comment]
Yes, that should probably do fine. I did not realize well enough the need to have a GitHub account... that is not ideal...
