### ISSUE TITLE
Physchem data linked to Nymark2015 data bundle

### ISSUE THREAD

**Issue by pennym** [enanomapper/data.enanomapper.net#22]
There´s an additional paper on the physchem and cytotoxicity of the materials in the Nymark2015 data bundle:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3933237/
Physchem: You´ll find a table (Table 1 - the three first materials) with composition info and specific surface area. But there´s also sedimentation and agglomeration info. These are maybe slightly difficult to extract...and there might not be standardized ways of reporting these parameters...
Cytotoxicity: Table 2 contains IC50 values, but I could also provide you with the raw data to include in the database
Radical formation: This is probably also more difficult to extract and may need separate discussions.

**Comment by egonw** [comment]
@pennym I have added specific surface area data and the IC50 values from Table 2. The raw data can be best uploaded to Figshare. (Mind the citation effect of uploading data [0]). There is a balance between having the IC50 values and the full dose-response curve. I have both in NanoWiki, but since I had no IC50 values yet, this makes a nice test case. The radical formation info we will first discuss and then open a new ticket.

**Comment by egonw** [comment]
I have sent new NanoWiki data to Nina, which includes this data.

**Comment by pennym** [comment]
Thanks Egon...
@vedina I can´t find the Nymark2015 data when searching for BEAS-2B, so I assume that info hasn´t been included, but it would be important to include especially in combo with what Egon sent you. Actually I have a file compiled with data from the Nymark2014 publication, which I uploaded to Figshare: https://figshare.com/articles/Tox_and_physchem_data_miRNAno_xlsx/2198986
I also have raw tox data, but I´ll send that to both of you, Nina and Egon. You can then check whether it would be better to have in a different format and I can then upload it to Figshare if necessary. I´ll send it by mail.

**Comment by vedina** [comment]
@pennym , the new NanoWiki is not yet in the database, sorry!

**Comment by egonw** [comment]
@pennym, can you review this screesnshot?

![image](https://cloud.githubusercontent.com/assets/26721/14979245/72a8d87e-1121-11e6-85f8-f74a19082201.png)

**Comment by egonw** [comment]
@pennym this is how time information is linked to an IC50 measurement:

![image](https://cloud.githubusercontent.com/assets/26721/14979366/206db8d0-1122-11e6-9483-9fbff634ac7b.png)
