### ISSUE TITLE
clarify difference between "Collect structures" and "List collected"

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#3]
When browsing a bundle for the "Collect structures" (the tab), there are two deeper tabs. First, it is too hard to notice, and the default often as formaldehyde; the "List collected" would be a better default.

![image](https://cloud.githubusercontent.com/assets/26721/9979862/7db41c20-5f82-11e5-8f19-844ea8dd266d.png)

But my real question is that I assume there is a reason why there are two variants of lists. Can this be clarified, please?

**Comment by vedina** [comment]
The "Collect" provdes means to run different searches and accumulate structures from these. The "List collected" is a list of structures selected from several rounds of searching. 

e.g. one can run exact search, similarity search, substructure search and select different structures. There will be different hit list from each query and only selected structures will appear in the "List collected" tab.  

This interface comes from a different use case than showing static collections of NM. Suggestions for dedicated UI are welcome!
