### ISSUE TITLE
what about an LD top category?

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#30]
With features/properties like owl:sameAs, rdfs:seeAlso (e.g. for linking to pages which mention an enm), skos:closeMatch, etc?

**Comment by vedina** [comment]
Could you clarify ?  Where it should appear - menu, bundle, or somewhere in the study JSON?

**Comment by egonw** [comment]
It should find its way everywhere, but in the GUI it could be another TAB (like TOX, P-CHEM, etc) and in the API it should likely be a separate call...

**Comment by vedina** [comment]
Well, TOX / P-CHEM / ENV / ECO-TOX are categories stemming form the ECHA guidance, and LD is not a study category at all. 

I agree it is useful to organise information and be somewhere in the API.
