### ISSUE TITLE
Error : Method Not Allowed

### ISSUE THREAD

**Issue by gebele** [enanomapper/data.enanomapper.net#31]
For any bundle view inside the Collect Structure tab I get : Method Not Allowed 
e.g. https://data.enanomapper.net/ui/assessment?bundle_uri=https%3A%2F%2Fdata.enanomapper.net%2Fbundle%2F1

**Comment by vedina** [comment]
Looking into it, likely related to the domain name change and policies.

**Comment by egonw** [comment]
I have the issue since a few days for some of the browsing too. Would a log out and log in solve the issues?

**Comment by vedina** [comment]
Seems related to https://github.com/ideaconsult/Toxtree.js/issues/183

**Comment by vedina** [comment]
This should be resolved now, please confirm.

**Comment by gebele** [comment]
For me this is solved. "No records matching the filter." and " - " for the entries is shown.

**Comment by vedina** [comment]
Fixed
