### ISSUE TITLE
rdf link returns json

### ISSUE THREAD

**Issue by gebele** [enanomapper/data.enanomapper.net#32]
For any bundle summary and property download rdf link content is returned as json.
e.g. https://data.enanomapper.net/bundle/1/summary, https://data.enanomapper.net/bundle/1/property

**Comment by vedina** [comment]
[https://data.enanomapper.net/bundle/{id}/property](https://data.enanomapper.net/bundle/1/property) now returns RDF properly

@egonw Could you help what RDF properties to use to serialise [bundle/{id}/summary JSON](https://data.enanomapper.net/bundle/1/summary?media=application%2Fjson) as RDF ?

**Comment by vedina** [comment]
can we close this?
