### ISSUE TITLE
the main nanomaterials should be general and not database specific

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#33]
E.g. it should not be "Harper2011 XX", but something like "TiO2 (32nm)". This can probably be autogenerated with some heuristics.

**Comment by vedina** [comment]
There is already a choice between `name` and `publicname` , where `name` is supposed to be specific (originates from the `company-specific-name-of-a-substanceiin-IUCLID5)` and `publicname` , which is supposed to be the generic name, known to the public. 

[JSON](https://data.enanomapper.net/substance/NWKI-566286ef-03eb-317a-8d9d-24fffefefc0b?media=application%2Fjson)

```
{

    "substance": [{
        "name": "Harper2011 9",
        "publicname": "Ag",
        "substanceType": "NPO_1892",
    ...
}
```

An easy workaround is for the search UI to list the public names first, and then optionally the specific name, e.g.  

![image](https://cloud.githubusercontent.com/assets/211190/13722015/1fa626ae-e840-11e5-81d7-aee87ca3fa55.png)

Autogeneration would be more appropriate for some sort of identifiers than names.

**Comment by vedina** [comment]
@egonw could you tell which property from NanoWiki to use as nanomaterial labels . Currently we use one of `mw:Property-3AHas_Label` and `rdfs:label` (whichever exists), but for some NM these are just integer numbers.

**Comment by egonw** [comment]
Yeah, the label is often what is used in the paper (those are often not clear enough and too bound to the paper; the wiki page name (what you have been using so far may be better)... I would suggest to take something like:

```
"$chemformula ($size, $wikiPageName)
```

**Comment by vedina** [comment]
@egonw  Does this look ok?

![image](https://cloud.githubusercontent.com/assets/211190/15633471/252bc94a-25b6-11e6-90ef-c7d1fdcadb0f.png)

**Comment by egonw** [comment]
Yes, except that I don't see the label...

![image](https://cloud.githubusercontent.com/assets/26721/15633517/9a2b5bbe-25ae-11e6-8232-fd05ab4c342d.png)

**Comment by vedina** [comment]
Right, this time labels are ignored, as for some NM they are not meaningful ... (like below)

![image](https://cloud.githubusercontent.com/assets/211190/15633792/b51dfd68-25be-11e6-8225-ebb4ee0793d5.png)

**Comment by vedina** [comment]
ok, next try

![image](https://cloud.githubusercontent.com/assets/211190/15633841/8287e3b8-25bf-11e6-8cbc-abee9bd71252.png)

**Comment by egonw** [comment]
Yeah, looks fine.

**Comment by vedina** [comment]
Shall we close this?  There are more improvements in the [new interface currently under testing ](https://solr.ideaconsult.net/dev/test-enm/) #45

![image](https://cloud.githubusercontent.com/assets/211190/17662611/659ed0e6-62ef-11e6-9c5c-f2fd3b1ca068.png)
