### ISSUE TITLE
indexing of references incomplete?

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#37]
Or is it just that it only shows a subset of things?

![image](https://cloud.githubusercontent.com/assets/26721/14168245/82f42a72-f721-11e5-932a-bd0984b70f4c.png)

E.g. I don't see all years appear in which the articles were published (see the NanoWiki cryptic substance codes). Also, some DOIs are missing, like that of the first in the result list.

**Comment by vedina** [comment]
The query has restriction to show only references with at least two NM (but this is rather arbitrary)

**Comment by egonw** [comment]
OK! I'll double check the papers to see if the missing DOIs have one or more materials...

**Comment by egonw** [comment]
Besides that, there was also that in NanoWiki not all nanomaterials were directly linked to DOIs, but only via the assay. That is fixed in NanoWiki v3.

See also: https://github.com/enanomapper/data.enanomapper.net/issues/54
