### ISSUE TITLE
clarification of errorValue

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#38]
A couple of study results have an "errorLevel". Can you specify the exact meaning of "errorLevel", is it eg a standard deviation, 95% confidence interval, ...?

**Comment by vedina** [comment]
could be any of these (or more), should be specified by the error qualifier. If not, means was not specified in the input source

**Comment by ghost** [comment]
Thanks! Unfortunately I am seeing a lot of entries without an "errQualifier", but I understand that it depends on the input source.
