### ISSUE TITLE
efficient retrieval of studies

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#39]
I am not sure, if I am missing something obvious. In order to get all studies for a bundle I am currently iterating over substances and retrieving the study for each substance. Is there a more efficient way to get all studies for a bundle with a single REST call?

**Comment by vedina** [comment]
One option is 

```
/bundle/{id}/dataset
```

**Comment by ghost** [comment]
I have tried before switching to studies, but datasets don't give the complete study details (with conditions, units etc. )

**Comment by vedina** [comment]
@helma forgot to add another option is to to use `RDF/XML`, `N3` and `JSON-LD` with `bundle/{id}/substance`. Also Excel export  `/bundle/{id}/substance?media=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` (but it's more suitable for human readable reports)

Will be adding optional support for this for the `JSON` mime type too.

**Comment by ghost** [comment]
I think something is wrong with JSON-LD serialisation: I could not find substance entries, although they are present in RDF/XML.

**Comment by ghost** [comment]
For a more long term perspective: Would you recommend to use the JSON or the JSON-LD representation? I have the impression that JSON-LD provides less detail at the moment, but ontology annotations can be useful.

**Comment by vedina** [comment]
Substances in JSON-LD are present and have prefix `"as" : "https://data.enanomapper.net/substance/"`

``` json
{
    "@id" : "as:XLSX-ffd24485-3b05-3afe-b6ff-547800723f71",
    "BFO_0000056" : [ ":measuregroup/XLSX-fa433d53-df49-4420-854a-fd59b58d39c5", ":measuregroup/XLSX-9c8b990c-b31c-493e-8d3e-e1d4fa9ab680" ],
    "source" : ":owner/XLSX-4bb81f08-059d-32ad-b5fd-71c6bcc6e0db"
  }
```

in `n3` the same looks like

```
as:XLSX-ffd24485-3b05-3afe-b6ff-547800723f71
        obo:BFO_0000056  <https://data.enanomapper.net/measuregroup/XLSX-fa433d53-df49-4420-854a-fd59b58d39c5> , <https://data.enanomapper.net/measuregroup/XLSX-9c8b990c-b31c-493e-8d3e-e1d4fa9ab680> ;
        dcterms:source   <https://data.enanomapper.net/owner/XLSX-4bb81f08-059d-32ad-b5fd-71c6bcc6e0db> .
```

(seems JSON-LD is less human readable than `RDF/XML` or `N3` :)

**Comment by vedina** [comment]
@helma  - regarding recommendations on file formats: 

 it depends, we have implemented and are using  `JSON` since several years (see [[1]](https://github.com/opentox-api/api-specification/issues/2) and [[2]](https://github.com/ideaconsult/examples-ambit/tree/master/ambit-json-docs)), while `JSON-LD` is pretty recent. However, the `JSON` is designed to match the internal [ambit](ambit.sf.net) data [model](https://github.com/enanomapper/nmdataparser/blob/master/ambit2.base.data.study.gif) , while all RDF serialisations are structured around BioAssayOntology data model.

**Comment by ghost** [comment]
Thanks! For the moment I will stick to JSON, maybe we will use JSON-LD later for GUI enhancements.
