### ISSUE TITLE
free text search

### ISSUE THREAD

**Issue by pennym** [enanomapper/data.enanomapper.net#40]
The free text search link opens a search that has already been done for zinc oxide. This may lead to visitors thinking that there is less data in the database than there really is, if they don´t notice it. Maybe it would be good to change the first page to an empty search displaying a summary of all the data in the database?

**Comment by vedina** [comment]
This is not so anymore.

**Comment by pennym** [comment]
Oh now I see, it´s when I choose the free text search from the scroll down menu on top...I´ve just automatically gone there without realizing I can choose it directly from the first page...so maybe fix the li8nk in the scroll down menu as well?

**Comment by vedina** [comment]
thanks, will fix the menu link

**Comment by vedina** [comment]
Fixed
