### ISSUE TITLE
Liu2011 06 lacks bioassay results

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#42]
While it does list the bioassay entries, the result/outcome value is missing:

![image](https://cloud.githubusercontent.com/assets/26721/14855175/0a4d87d0-0c93-11e6-939f-bf9b0bc5bd04.png)

See: https://apps.ideaconsult.net/enanomapper/substance/NWKI-8ef21404-e101-37c8-8206-32f526d75012/study

**Comment by egonw** [comment]
This is what it looks like in NanoWiki:

![image](https://cloud.githubusercontent.com/assets/26721/14869803/40978d98-0cd6-11e6-846f-b309e1ce561f.png)

And this is one of the measurements:

![image](https://cloud.githubusercontent.com/assets/26721/14869847/68d7fd06-0cd6-11e6-9858-c8d96dc93453.png)

The RDF for that looks like:

![image](https://cloud.githubusercontent.com/assets/26721/14869858/85a14a46-0cd6-11e6-9ba1-c85c27febc2e.png)

The expected result is a String like classifier. Is that possible in AMBIT?

**Comment by egonw** [comment]
Still applies with the NanoWiki 3 import.

**Comment by egonw** [comment]
OK, Nina and I uploaded NanoWiki 4 today, and I still don't see the end point value :(

**Comment by vedina** [comment]
It's there ([see the JSON](https://data.enanomapper.net/substance/NWKI-8ef21404-e101-37c8-8206-32f526d75012/study?media=application/json))  , the display needs to be configured to show the text value in addition to (the default) numeric one

**Comment by egonw** [comment]
Ah, wonderful! I did not think of checking that last night... btw, I'm pretty sure the data really wasn't there before, so the new upload actually fixed it.
