### ISSUE TITLE
Improving user friendlyness of the eNM database

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/data.enanomapper.net#45]
These issues are based on a science cafe presentation at UM (slides: https://docs.google.com/presentation/d/1Qq6FEqkqEPNFFZgxxLnBpgaMFBWkQnDIXGe7ihhLSnY/edit#slide=id.p4).

The main feedback was that the database needs to become much more user-friendly (users in that case: biologists, bioinformaticians). The first page is ok -  they liked the square fields asking what do you want to do and directing to the sub-search possibilities.

Recommendations in detail:
- reduce distracting information like identifiers and access numbers and cryptic study names and add clear names like nanoparticle type, assays used, endpoints.
- replace DOI, study identifiers and ORCID numbers by names of authors, titles or names - make it more human-readable
- make the search and filter function more user friendly: The new free text search function is on the right way, if you know to klick on the items in the field on the left side (e.g. filter for data source, cell type, assay, etc.) - this should be implemented to all search functions like components, name etc.
- filters added to the search (and filter ranges if that is possible (e.g. nanoparticle size 10 - 50 nm)) and they should be clearly visible during klick-through the search
- more user guidance for upload function - e.g. stepwise and with explanation (invite user to annotate data properly with ontology terms).

@vedina @egonw

**Comment by egonw** [comment]
Oh, thanks! I was just about starting to do this, after some other enm ground work...

**Comment by fehrhart** [comment]
The new free text search is already quite on the right way. I have here an example about nice choosing, selecting and filtering of items from a commercial web page 
![search function](https://cloud.githubusercontent.com/assets/11389574/14916652/2928d3e2-0e1b-11e6-9ee3-0a10a4355a32.gif)

(Zalando.nl - shoes - forgive me :) )

**Comment by vedina** [comment]
assigned @thejonan - details to be discussed

**Comment by vedina** [comment]
TODO: Hierarchical display of categories (endpoints , but also species/cells, see #53) )

**Comment by vedina** [comment]
New interface is available at https://solr.ideaconsult.net/dev/test-enm/ for testing. Please comment.

**Comment by egonw** [comment]
(Nice!)

@fehrhart, can you help Nina with the following? For data with cell lines, we also know the species (several human cell lines). But currently only rat shows up as species:

![image](https://cloud.githubusercontent.com/assets/26721/17662208/44266bb4-62e4-11e6-8aa5-c95ffa722557.png)

Freddie, can you provide @vedina with a table with (cell line, species) tuples?

**Comment by fehrhart** [comment]
done - almost
https://docs.google.com/spreadsheets/d/1Aksw6Q0es8uza8P0JC-WYPmiiOIQB6A5yTloRICHIqQ/edit?usp=sharing

Need to look up original data for mES. Most likely mouse embryonic stem
cell or something like that... but I will check.

**Comment by fehrhart** [comment]
P.S. clicking on 2015 gives error 404 - see image
![picture2](https://cloud.githubusercontent.com/assets/11389574/17663299/f84ea8e8-62eb-11e6-9f11-8b5921d8dba6.gif)

**Comment by vedina** [comment]
@fehrhart thanks - that's due to missing DOI in MODENA source. 

Actually we are considering removing the experimental results listing altogether, as they are 1) not all available results are returned by the search engine 2) not formatted with all the details.  We would leave only link to the database itself, but this will remove the references links as well (i.e. that 2015 link) .
Will this be ok from your point of view?

**Comment by vedina** [comment]
some graphical indication that there is more I can select from (scroll down to) for pivot widgets (e.g. TOX)

**Comment by fehrhart** [comment]
I like it. The looking for data and application of multiple filters is much
more intuitive now.

Best regards,
Freddie

**Comment by fehrhart** [comment]
Is this intended? If I click on Material it will open a new window with the information. If I then click on Composition or Study it will refresh the window of Material instead of opening a new one.
![clipboard02](https://cloud.githubusercontent.com/assets/11389574/17801817/9bf8881c-65ec-11e6-8876-f345c5c21977.jpg)

**Comment by vedina** [comment]
I think it is intentional - otherwise we'll have millions tabs opened by few clicks. One can always use "open in new tab" if needed.     But if it is really inconvenient it's easy to modify to open new tab every time.

**Comment by egonw** [comment]
@fehrhart, can you test if all your issues have now been addressed? If not sufficiently, please file a new bug report with further suggestions.

**Comment by fehrhart** [comment]
Re-checking the issues...

I really like the search function now!
About the cryptic names, well, if the cheminformatics guys like it I am fine with it, too.

I see here 2 unsolved issues left to be discussed:
- is filtering by range still a factor to discuss? e.g. phys-chem, particle size distribution: give a range e.g. 5 - 10 nm
- Improving data upload - is it intended that anyone is able to upload? or only members of eNM/associated/trained people? 
  If untrained people should be able to upload it would be very helpful to provide the spreadsheet and give an example - so people can see how to prepare their data.

@egonw @vedina

**Comment by vedina** [comment]
@fehrhart filtering by range is under development 
for upload we'll be working to provide templates and guide.

**Comment by vedina** [comment]
Closing, as all improvements (including range filters) are deployed at https://search.data.enanomapper.net/new/index.html . Fore new issues, please enter new tickets under the `improved search UI ` milestone.
