### ISSUE TITLE
Idea for new top line

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/data.enanomapper.net#48]
Idea for the top line: 
Home (click on logo was not intuitive for all) 
Search (sub menu - nanomaterials, endpoints, components, data sources...)
upload data
for developers (including API, documentation)
help

**Comment by vedina** [comment]
@fehrhart which categories the bundles list should appear ?

**Comment by fehrhart** [comment]
I thought about bundles being data source or resources - as discussed in the e-mails.

**Comment by vedina** [comment]
Resources yes, but not necessary data sources. They are simply grouping of substances and endpoints, as described in the [bjnano paper](http://www.beilstein-journals.org/bjnano/single/articleFullText.htm?publicId=2190-4286-6-165#datasets-of-substances-bundles)

**Comment by fehrhart** [comment]
Is this something only developers would need? then maybe in the developers section
If not, I would propose it to be a sub-menu of search

**Comment by vedina** [comment]
Not only developers - the bundles view is the main page presenting overview of the available data sets, not sure it fits well in search, as it's not really searching.

What about menu "data collections" menu?

**Comment by vedina** [comment]
@fehrhart @egonw see the updated menu at https://apps.ideaconsult.net/enanomapper/

**Comment by fehrhart** [comment]
Looks good for me!

Just wondering whether Algorithms and Models are best in "for developers". @egonw or @dphilip - would you look for that there?

**Comment by dphilip** [comment]
The "for developers" tab seems a nice step to organise items not relevant to users not keen on behind-the-scenes aspects. Having APIs together with algorithms is a little unexpected, but I guess these two groups have greater ease at navigating the menus, so let's keep it that way!

**Comment by ghost** [comment]
I had a quick look at For developers - > Resources -> Datasets and could not find any enm datasets. The Datasets per endpoint page has zero entries. Most of the resources seem to be for compounds instead of nanoparticles.

**Comment by vedina** [comment]
@helma Yes, datasets are on compounds, not on nanoparticles, for the later we have bundles (now menu Data collections). The datasets / algorithm / model resources are old OpenTox resources (this is why the previous menu was listing them under "OpenTox" menu.

`Datasets per endpoint` correctly has zero entries since there are no endpoints in these datasets, they only contain chemical structures. We can remove this menu item indeed.

**Comment by vedina** [comment]
Dataset menu is simplified now , with (hopefully) proper description of the menu items https://apps.ideaconsult.net/enanomapper/

**Comment by fehrhart** [comment]
I think we can close that one now?
