### ISSUE TITLE
Data presentation

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/data.enanomapper.net#49]
Empty fields look a bit crappy - they waste space on a webpage, leaving less for relevant information. If there is no information for a column maybe think about not showing the field at all instead of empty fields.

**Comment by vedina** [comment]
Please leave an example (link or screenshot)

**Comment by fehrhart** [comment]
Examples:

![no data at all](https://cloud.githubusercontent.com/assets/11389574/14916759/bb94b566-0e1b-11e6-8fbf-c1cf3527f589.gif)
![empty column](https://cloud.githubusercontent.com/assets/11389574/14916760/bef0fbe8-0e1b-11e6-99cb-f934a94ef632.gif)

**Comment by vedina** [comment]
- The first screenshot  (with UUID starting with CNLB) is weird, where does it come from ? There should be no entry with "CNLB-" (meaning caNanoLab) prefix in the data.enanomapper.net , this is perhaps a wrong link in the free search page (yes, fixed 32a56615f47f204726cfd402043133a51296a4fc) .
- The missing column for EC number means just this information was not provided, normally all substances in EU should have such number. (see https://en.wikipedia.org/wiki/European_Community_number)

**Comment by vedina** [comment]
considering this fixed, there will be no non-enm links from the search page , resulting into empty fields as in the first screenshot. For the second missing information is normal.
