### ISSUE TITLE
NanoWiki "C" compounds should really be "[C]"

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#5]
It's not methane, but pure carbon compounds of unknown size.

**Comment by vedina** [comment]
Fixed by [r6841](http://sourceforge.net/p/ambit/code/6841). 

Will render as 
![cdk](https://cloud.githubusercontent.com/assets/211190/10131046/f2b18bb2-65d5-11e5-82d9-946dd6af02e1.png)

**Comment by egonw** [comment]
I checked the NanoWiki and the "Property:Has Chemical Composition" reflects a chemical formula, but not strictly even that. But it's certainly not a SMILES. Since the importer is fixed and NanoWiki does not say it's a SMILES (it uses "Property:Has SMILES" for that), I will close this issue.
