### ISSUE TITLE
add data from http://www.ncbi.nlm.nih.gov/pubmed/23659652

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#50]

**Comment by egonw** [comment]
I added the physchem props and references to GEO.

**Comment by pennym** [comment]
@egonw, is this data now in the database? or does that need Ninas action? If it´s there can you give me the link. I can´t find it by free text search...

**Comment by egonw** [comment]
I think @vedina has not updated to the latest NanoWiki yet, and I am still learning myself how I can do that...

**Comment by pennym** [comment]
right, so whenever it is there, maybe you can update the link in the Chipster tutorial. I added a comment in the document under review. Until then I just linked to the database itself.

**Comment by egonw** [comment]
@vedina, could you please load the NanoWiki data snapshot once more?

**Comment by egonw** [comment]
The DOI is 10.3109/17435390.2013.803624 but when I search even for just the publisher part (10.3109) I do not get any results... (also not for 10.1021 = ACS). Will file a bug report for this.

(But searching for "Tilton2014" shows two materials...)
