### ISSUE TITLE
More physchem data linked to Nymark2015

### ISSUE THREAD

**Issue by pennym** [enanomapper/data.enanomapper.net#51]
Could also this data be added in relation to the materials in the Nymark2015 study. It is linked to another study (http://www.ncbi.nlm.nih.gov/pubmed/24438343), but from the same materials. 
https://figshare.com/articles/Tox_and_physchem_data_miRNAno_xlsx/2198986
(From the physchem sheet in the file)

In addition there are 5 other characterized materials, than the ones already in the eNM database in relation to Nymark2015.

**Comment by egonw** [comment]
ping @vedina, any chance you can load NanoWiki 3 this week? I like to use this data in D4.4 due end of this month, a full draft due end of this week.
