### ISSUE TITLE
No species and results in the new free text search 

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/data.enanomapper.net#53]
There is no content offered for species and results in the new free text search. I suppose results must be offered in the data (or not) but species should be provided with the information of the cells used? 

![species](https://cloud.githubusercontent.com/assets/11389574/15107516/730ac378-15d0-11e6-8b77-5180c7f382b7.gif)

**Comment by vedina** [comment]
TODO :
- update the search index with species info (where possible, only caNanoLab has such information, there is practically none in the data.enanomapper.net)
- update visualisation , see #45

**Comment by vedina** [comment]
Fixed in https://search.data.enanomapper.net/new/index.html
