### ISSUE TITLE
frontpage improvements - please vote

### ISSUE THREAD

**Issue by vedina** [enanomapper/data.enanomapper.net#55]
Please vote for the following options to improve the frontpage of https://data.enanomapper.net/ 

1) Replace the 6 boxes by icons
2) Replace the 6 boxes by links 
3) Leave as it is

@egonw @helma @dphilip @vedrin @rautenberg @fehrhart @pennym (and everybody else)

Details in the comments below:

**Comment by vedina** [comment]
# Replace the 6 boxes by icons
- Search by biological efects
  ![logo2](https://cloud.githubusercontent.com/assets/211190/15115288/f5cbad5a-1606-11e6-9c95-38d19f71ab1d.png)
- Search by identifier - similar icon, ID instead of IC50
- Search by citation - similar icon, DOI  instead of IC50
- etc. (suggestions welcome)

**Comment by vedina** [comment]
# Replace the 6 boxes by links

(and general page cleanup)

![enanomapper2](https://cloud.githubusercontent.com/assets/211190/15115389/671fb92e-1607-11e6-91a1-3b0355b7e127.png)

**Comment by egonw** [comment]
Both look like a great improvement to me! Happy with either.

**Comment by GTsiliki** [comment]
2nd choice looks better to me, but they both are good improvements

**Comment by ghost** [comment]
I prefer the links version, but thats a matter of personal taste.

**Comment by dphilip** [comment]
2nd choice looks best I think! The UI keeps improving!

**Comment by pennym** [comment]
I agree, I would keep it simple with the 2nd choice.

**Comment by vedina** [comment]
As there is consensus on the 2nd option, https://apps.ideaconsult.net/enanomapper/ is now updated accordingly.

Thanks to all  for the comments (and to @kerberizer  for suggesting the links option and making the mockup :)
