### ISSUE TITLE
Ontology and data visualisation available for testing and feedback

### ISSUE THREAD

**Issue by vedina** [enanomapper/data.enanomapper.net#59]
Please find our interactive visualisation of ontologies and data summaries. Feedback welcome!

https://search.data.enanomapper.net/treedemo/index.html

It is also available via `For developers` menu at https://search.data.enanomapper.net/ 

![untitled](https://cloud.githubusercontent.com/assets/211190/16000319/5b198246-3154-11e6-86de-49e15a091a0d.png)

The JavaScript widget (developed by @thejonan / Ideaconsult) can display any hierarchy, provided in JSON. 
- The [demo JSON files](https://github.com/enanomapper/data.enanomapper.net/tree/gh-pages/treedemo) for the ENM, BAO, GO and ChEBI ontologies are generated by reading the ontologies form BioPortal and generating the hierarchy starting from `owl:Thing` and using the `rdfs:subClassOf` to build the tree [[code here]](https://github.com/enanomapper/nmdataparser/blob/master/src/test/java/net/enanomapper/parser/test/RDFsmasher.java).
- The data.enanomapper.net example displays the same information as the in this page (the box at the left)
- The protein classification JSON is generated from the corresponding table of ChEMBL21 database.

The next steps would be to explore different grouping schemes to visualise the data in https://data.enanomapper.net and link back from the visualisation to the data entries. Suggestions for new functionalities are appreciated!

**Comment by dphilip** [comment]
Hi Nina, 

it looks very nice!
One suggestion could be to make the font size depend on the size of the cell and/or give the user some control over it (perhaps with the +/- keys).

**Comment by egonw** [comment]
Yeah, looks great! I know this is likely pushing it, but what about coloring the various tree nodes and/or subtrees according to some data set, so that all tree parts are gray except those subtrees that applies to some data set annotation?

**Comment by pennym** [comment]
Indeed, nice! And Egon´s suggestion sounds good. Ingenuity Pathway Analysis does something similar. Maybe you can find some ideas from their documentation...even if it is maybe very vague, since the program is commercial...which also means taking ideas from them might be limited...?
http://www.ingenuity.com/wp-content/themes/ingenuity-qiagen/images/ipa/screens/downstream-effect-analysis.jpg

**Comment by vedina** [comment]
@pennym , yes, the Ingenuity Pathway picture is a TreeMap, and our visualisation is also based on a Treemap, but  a bit extended. 

@thejonan we may consider showing details &  tableview & filtering
