### ISSUE TITLE
User friendly search for nanoparticles using their names in the database

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/data.enanomapper.net#6]
I would propose to add common nanoparticle names (gold, silver, carbon nanotube...) including their synonyms and elemental name (Au, Ag, C) to the "substance name". 

Examples:
If you use a name based search, it is currently not possible to find any "gold" (or "Gold", or "Au") nanoparticles - while there are more than 100 NPO_401 (= gold nanoparticles) available in the database. 
The search gives results for "SiO2" but fails to give the same items when you search for "silica dioxide".
The search for "silver" does not give any result, "Ag" is recognized if Ag is (by accident) part of the substance name but you still get much less hits than using the term NPO_1892 (silver nanoparticle).

**Comment by vedina** [comment]
This should be closed with the search application at https://search.data.enanomapper.net/
