### ISSUE TITLE
search UI - add to basket, no mouse hover links please

### ISSUE THREAD

**Issue by vedina** [enanomapper/data.enanomapper.net#64]
Please don't use mouse hover for any actions.   

![image](https://cloud.githubusercontent.com/assets/211190/17019503/46839876-4f45-11e6-843d-b7d3c59a1e59.png)

 For basket add/remove, provide the link, perhaps with a color different than the main content. 

Also, when a NM is within the basket, clicking anywhere removes it, which makes all the links within the entry unusable.  Please add a specific link/button to remove an item from the basket.

**Comment by thejonan** [comment]
I hope this way is better.
