### ISSUE TITLE
Searching nanomaterials / studies

### ISSUE THREAD

**Issue by mhegi** [enanomapper/data.enanomapper.net#7]
On the page "https://apps.ideaconsult.net/enanomapper/query/study" would it make sense to:
- have one checkbox selected by default? (maybe the most frequently used?) - so, there are results at the first click in the table.
- In case multiple checkboxes are selected, could we show in the result first the hits matching all categories, then also the ones matching only partly? (OR selection)
- We could update the page on-click of the checkbox, so we could remove the button "update results"

**Comment by vedina** [comment]
- `Particle size distribution` is now selected by default 
- what do you mean by 'matching partly' ? '`OR` does not guarantee 'partial match'.  `AND` selection is typical in similar interfaces, as the goal is to restrict the search space (and ideally the particles should have as much experiments as possible). `OR` could be added of course
- Update  `on click` is disabled intentionally, for performance reasons. Could be redesigned for [D3.2 milestone](https://github.com/enanomapper/data.enanomapper.net/milestones/D3.2%20Extended%20search%20capabilities)

**Comment by vedina** [comment]
Please test http://enanomapper.github.io/data.enanomapper.net/

**Comment by vedina** [comment]
closed as the search.data.enanomapper.net is now the free text search interface
