### ISSUE TITLE
list range, rather than only lower limit

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#71]
I really like the new nanomaterial titles, and also that the size shows up in the title, like in this search result list 

![image](https://cloud.githubusercontent.com/assets/26721/17918877/17472d18-69c9-11e6-8d01-6c8d08e77be1.png)

However, in these two examples only the lower limit is given, while the upper limit from the range is given in the data.enanomapper too:
- https://data.enanomapper.net/substance/NWKI-c0927a67-d21d-37e8-932d-fb1607e58aee/study
- https://data.enanomapper.net/substance/NWKI-e866549e-38cf-3b98-a0b1-a483e275d261/study

I suggest the SearchUI to list the full range info instead.

**Comment by vedina** [comment]
Thanks :) 
The size is a bit of a hack, as it is min across all available experiments. Have to reindex to include a second value.

**Comment by vedina** [comment]
implemented in the new search interface https://search.data.enanomapper.net/new/index.html
