### ISSUE TITLE
data.enanomapper.net is down with DNS issues

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#78]
```
This site can’t be reached

data.enanomapper.net’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by egonw** [comment]
We are exploring the cause.

**Comment by vedina** [comment]
The site is up and running, however there is DNS server issue for `data.enanomapper.net domain`, the DNS maintainers (Douglas Connect) are notified

**Comment by egonw** [comment]
The problems seem resolved and the websides are back online.

Thanks to everyone for their involvement and prompt responses!
