### ISSUE TITLE
New search interface proposal for comments

### ISSUE THREAD

**Issue by vedina** [enanomapper/data.enanomapper.net#8]
- This is a proposal for comments for the [D5.5 User application for searching and downloading eNanoMapper data](https://github.com/enanomapper/data.enanomapper.net/milestones/D5.5%20User%20application%20for%20searching%20and%20downloading%20eNanoMapper%20data)

![search_ui](https://cloud.githubusercontent.com/assets/211190/10575576/1879862e-7666-11e5-88a7-bd1836e039db.png)
### Free text search
- search box (with autocomplete) on the top
### Summary for several groups on the left
- Which groups ? Are the ones at the screenshot sufficient? Any to be removed?  Any others to be added?  
- Summary representation. 
  - Tag cloud as at the screenshot vs multiselection checkboxes. 
  - Should there be any hierarchy (e.g. for NM types or assay types) ?
  - Should there be a group for selecting e.g. particle size ranges? 
- Click on any link on the left adds the criteria to the `Current selection` and filters the query.  Any other suggestions?
### List of nanomaterials on the right
- Nanomaterial name - click on the name leads to the full NM record, e.g. [NM-111](https://apps.ideaconsult.net/enanomapper/substance?type=&search=NM-111)
- Summary of studies per NM . Click leads to the full study record
  (currently shown only for the first NM in the list)
- Suggestions welcome

**Comment by egonw** [comment]
I like it! I would suggest:
- using labels instead of NPO_xxx codes
- have the ability to "sort by", e.g. alphabetical on name, on size, year(!), ...
- the refs could use the DOI without the http://dx.doi.org/

**Comment by vedina** [comment]
Thanks!
- For `Sort by year` do you mean the year of the experiment ?  What if we have > 1 size measurement experiment per NM entry?

Related question 
- Should the entries in the list at the right be
  - nanomaterial  (with many studies)
  - single study (possibly with many replicates) ?

**Comment by vedina** [comment]
Also queries as per
- https://github.com/enanomapper/ontologies/issues/32 
- https://github.com/enanomapper/ontologies/issues/33

**Comment by egonw** [comment]
@vedina, year of experiment (disregard anything older than 2 years, because current methods are much more accurate). BTW, a tag cloud of 'year' may be an option too.

Regarding the second question, I'm tempted to say nanomaterial as entry point... that seems to be the common denominator...

**Comment by lucfar** [comment]
The interface looks OK to me, having the possibility of multiple selection, getting the summary in one page etc. 
The categories hierarchy, its fine - normally should have an order as: identification, characterization, assay, results...and yours follows this  logical structure. Perhaps after using/testing will give me other ideas, etc.
One comment: your search in the screenshot was based on NPO code. A user like me probably will search for e.g. 'ZnO' or 'zinc oxide'. If I search now in the https://apps.ideaconsult.net/enanomapper/# I get different results: 'ZnO' search shows the NaoWiki data, while 'zinc oxide' shows the MARINA data. Maybe I'm wrong.

**Comment by filipd** [comment]
It offers a nice set of features!
Some ideas that could provide additional functionality, although they are covered by full-text search:
1. Searching by test species could be useful.
2. Search for specific guidelines.

**Comment by pennym** [comment]
I also like it!
I agree with Egon that at this stage it may be better with NP labels instead of NPO codes, but later when the ontology gets more widely spread it might actually be good with the NPO codes, since the output from other analyses may be an NPO code or a list of NPO codes, which provides a more standardized way of searching, avoiding e.g. problems with different results popping up for ZnO and zinc oxide.
No other comments at the moment...they might come after a more hands-on test.

**Comment by ghost** [comment]
Overall I think that the search interface looks very good and usable!

I am listing below a few answers to Vedins questions and a couple of things that I did not grasp immediately and could be confusing for other novice users.

#### Groups:

> Which groups ?

  The difference between Assay types and Endpoints might not be immediately obvious. I could live without Assay types, but there are probably other use cases where this group is important.

  What is the purpose of the result section?

> Tag cloud as at the screenshot vs multiselection checkboxes?

  One thing I have stumbled upon initially was the font size in the text clouds. They might give the impression that large fonts indicate selected items, but I assume they indicate frequencies. 
  It might be possible to skip the "Current Selection" part if fonts indicate selections, but that could be confusing for others.

  I am not sure if the usability of tag clouds scales well for large lists, but I like their visual appearance.

> Should there be any hierarchy (e.g. for NM types or assay types)?

  I find them useful e.g. for data aggregation and could use them for NM types and assays/endpoints. IMHO low priority.

> Should there be a group for selecting e.g. particle size ranges?

  I can see use cases, but again low priority.

I agree with Egon and others that clear text names should be preferred over IDs, abbreviations and URIs (maybe even DOIs if titles or authors fit into the tag cloud).

#### Current Selection:

I can deduce that BAO 0002993 means "Cytotox Assay". Is BAO 0002169 "PARTICLE SIZE"? Clear text names could make the interpretation easier.

#### Results:

  I am confused that the first (NM-111) entry has a different visual appearance than other entries? It also presents 4 endpoints, but the query has only 3. 

  Entries for the other nanomaterials contain only results for PARTICLE SIZE. What about the other selected endpoints, are they empty?

  Export facilities (json,csv) could be useful.

**Comment by vedina** [comment]
Thanks to all for the comments!

The new interface can be tested [http://enanomapper.github.io/data.enanomapper.net/](http://enanomapper.github.io/data.enanomapper.net/).
- NPO codes are resolved to ontology labels @egonw , @lucfar , @pennym 
- The refs use the DOI without the http://dx.doi.org/  @egonw
- The free text search should behave user friendly, e.g. `zinc oxide`, `zno`, `NPO_1542` should give the same result , also for any other phrase. @lucfar (and others) let me know if you find a search query which do not behave as expected.
- The assay categories are split into phys chem and tox.. The green tags within each category are assay types, the blue tags are endpoints. @helma please check if this makes sense.
- The color part of the tag extends on hover and shows the number of entries having the tag. For endpoints there is a tooltip showing min/max values .
  ![image](https://cloud.githubusercontent.com/assets/211190/12712041/dd9f0a8c-c8cd-11e5-97e3-a1955a1896b7.png)
- Searching for species and protocols is covered by the text search, but also there is a widget showing tags for protocols and species (note there is really no species data in the database at the moment). 
- The appearance of all entries is uniform @helma 
- The missing results reported by  @helma was a bug, fixed.
- Linking to the export facilities of data.enanomapper.net is under development @helma 
- Searching can be done by free text as well as ontology codes @pennym 
- Tag clouds replaced with tags @helma
- Hierarchical display will be developed in a future version (the query returns hierarchical info already, the visualisation needs to be implemented).
- Note limited number of endpoint values are shown, for full display follow the corresponding links to the database.
- The database content will be updated this week 

Closing this ticket, please open new tickets when reporting issues on the new search page.
