### ISSUE TITLE
RDF Turtle download for data for a single nanomaterial

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#80]
The data can now be downloaded in various formats, but not RDF (except for JSON-LD which uses a different model?). Or not according to the icons, anyway.

![image](https://cloud.githubusercontent.com/assets/26721/19189445/592d26dc-8c98-11e6-820e-049d44574c79.png)

**Comment by vedina** [comment]
Could you check the N3 (icons are indeed missing, sorry)
https://apps.ideaconsult.net/enmtest/substance/NWKI-202b322d-51c9-3d73-a049-1e4019f8ddad/study?media=text/n3

JSON-LD  should be the same model.

**Comment by vedina** [comment]
RDF download icon added.

**Comment by vedina** [comment]
should we close this?
