### ISSUE TITLE
the OpenAPI for data.enanomapper.net does not include RDF mime types

### ISSUE THREAD

**Issue by egonw** [enanomapper/data.enanomapper.net#83]
I do observe there is JSON+LD there, but not sure if this is in the RDF format of the new export... and if possible, I like Turtle available too...

![image](https://cloud.githubusercontent.com/assets/26721/19721247/c21e58d6-9b71-11e6-84c7-dc181c77c2c2.png)

**Comment by vedina** [comment]
Done in http://sourceforge.net/p/ambit/code/7905 , deployed on https://apps.ideaconsult.net/enmtest
