### ISSUE TITLE
Request for comments on Substances and studies RDF serialisation

### ISSUE THREAD

**Issue by vedina** [enanomapper/data.enanomapper.net#9]
RDF serialisation of experimental data, following [BioAssay Ontology structure](http://bioassayontology.org/) is available on enanomapper database test instance only so far.
- NanoWiki [RDF/XML](https://apps.ideaconsult.net/enmtest/bundle/1/substance?media=application%2Frdf%2Bxml) [N3](https://apps.ideaconsult.net/enmtest/bundle/1/substance?media=text/n3) and [JSON-LD](https://apps.ideaconsult.net/enmtest/bundle/1/substance?media=application%2Fld%2Bjson)

@helma @rautenberg @egonw @G-Owen

Related to https://github.com/enanomapper/ontologies/issues/37

**Comment by ghost** [comment]
I did not have to parse the RDF, but I had a brief look at the N3. It looks well structured and intuitive, but I could not open the URIs (curl returns a 405 error, in the browser I can see only the front page although I am logged in with my OpenTox account). As we are avoiding RDF at the moment I cannot judge the technical implementation and would leave that to real RDF users. Do you plan to support BAO in JSON serialisations too?

**Comment by vedina** [comment]
while this is first attempt to use BAO, all URIs besides substances ones are not resolvable intentionally (RDF does not  require resolvable URIs AFAIK) . This RDF serialisation follows the BAO ontology model (with assays, measure groups,endpoints etc., as used in PubChem RDF). This is different that the JSON data model used elsewhere in the database.  Some BAO terms are already used in JSON (e.g. for substance type and assay annotation), but the data model is different and there are no plans to change it.    But generating JSON-LD based on the same BAO model is a good idea.

The main purpose of this RDF serialisation is to be able to dump the content into a triple store and enable SPARQL queries (for the real RDF users of course, the rest of us stay with JSON ;)

**Comment by ghost** [comment]
Should I ask Denis or Micha to import it into 4store and report any problems?

**Comment by vedina** [comment]
@helma yes, please

**Comment by vedina** [comment]
Thanks to Apache Jena 2.13.0 support and @helma asking for JSON with BAO, now there is JSON-LD serialisation with the same BAO model. MIME type `application/ld+json`

**Comment by gebele** [comment]
Successfully imported the NanoWiki [RDF/XML](https://apps.ideaconsult.net/enmtest/bundle/1/substance?media=application%2Frdf%2Bxml) to the 4store for testing.
Data graph is: `GRAPH <https://purl.enanomapper.org/nanowiki`.

**Comment by rautenberg** [comment]
As an example to export the graph data again, I did a test with 

```
CONSTRUCT { ?s ?p ?o } FROM <https://purl.enanomapper.org/nanowiki> 
WHERE 
{ ?s ?p ?o }
```

or by curl (mind the escaped spaces and brackets in the query command) with:

```
curl -X GET -ik -u username:password "https://purl.enanomapper.org/sparql/?query=CONSTRUCT%20\{%20?s%20?p%20?o%20\}%20FROM%20<https://purl.enanomapper.org/nanowiki>%20WHERE%20\{?s%20?p%20?o\}"
```

and get different formats by adding "&output=format" 
e.g.: **&output=text**  for turtle or **&output=xml**  for RDF XML 

```
curl -X GET -ik -u username:password "https://purl.enanomapper.org/sparql/?query=CONSTRUCT%20\{%20?s%20?p%20?o%20\}%20FROM%20<https://purl.enanomapper.org/nanowiki>%20WHERE%20\{?s%20?p%20?o\}&output=text"
```

output=json do not work with 4store as it is a _CONSTRUCT_ query

**Comment by gebele** [comment]
For some data RDF sructure isn't valid for the triple store. Message is "rdf:Description is forbidden as a property element" which is probably the part rdf:Description as property of a rdf:Description. This affects rdf for /dataset and /matrix where rdf:Description is used to describe the label, value and unit as property of a rdf:Description. @vedina

**Comment by egonw** [comment]
Nina, I have started looking at the data. I took this approach:
1. boot a Blazagraph 2.1 server with their downloadable jar
2. loaded the RDF for NanoWiki bundle
3. started to make queries

In the below comments, I will follow the [Open PHACTS RDF Guidelines](http://www.openphacts.org/specs/2013/WD-rdfguide-20131007/)

About step 0, please include the metadata, such as license etc, as a VoID statements, e.g. as outlined in the [Open PHACTS data sets description](http://www.openphacts.org/specs/datadesc/).

Thinking about step 1-3, I do not find all the classes/types and predicates I would expect. For example, I don't see a 'substance' type, or a predicate to specify the SMILES. It would be good to map the key types from your database to the corresponding classes. Looking at the URIs, I guess you have 'assay', 'reference', and 'substance' at least. These map to a BAO, BIBO, and CHEBI class respectively.

Step 4 is simple: we use our own ontology :)

Step 5 we will get to soon; that's part of the Linked Data work.

Step 6 you are already doing, and that I could load it into Blazegraph suggests the quality is good and the RDF has at least underwent some kind of validation with that already. The SPARQL queries UM and the EBI will develop will further validate the output.

Step 8 is already defined: the SPARQL end point, and the RDF download files AMBIT provides.

Step 9 is the VoID header I referred to at the start, and steps 10 and 11 we get to when we write up the RDF export.

So, I think the first things are to give things types. Predicates you already use a few useful ones from BAO.

So add triples like: measuregroup:NWKI-f888f18c-4f44-4365-94ba-0bdeb0e73501 a bao:BAO_0000040

The endpoint/IDxxxx I need to check with BAO...

Substances are rdf:type CHEBI:59999

Reference should probably be bibo:Document

**Comment by egonw** [comment]
I would also recommend using some 'has part' to link an substance to a component.

For example, https://data.enanomapper.net/substance/NWKI-002f5129-d46a-39c7-8f26-5626aec2174e has a core, but this data is not found in the RDF.

**Comment by egonw** [comment]
Looking at conformers, with the SMILES etc, I propose to use the CHEMINF like PubChem-RDF does. See [the paper](http://link.springer.com/article/10.1186/s13321-015-0084-4).

**Comment by vedina** [comment]
Just for the record:
- the AMBIT class generating the RDF is [SubstanceRDFReporter](https://svn.code.sf.net/p/ambit/code/trunk/ambit2-all/ambit2-rest/src/main/java/ambit2/rest/substance/SubstanceRDFReporter.java)
- and the PubChem / BAO RDF the current AMBIT serialisation is trying to implement is at https://pubchem.ncbi.nlm.nih.gov/rdf/
- AMBIT issue https://sourceforge.net/p/ambit/feature-requests/99/

**Comment by vedina** [comment]
- Added RDF types for substances, assays, endpoints , protocols and measure groups [r7686](https://sourceforge.net/p/ambit/feature-requests/99/)
- Deployed at [enmtest](https://apps.ideaconsult.net/enmtest/bundle/1/substance?media=application%2Frdf%2Bxml)
- Added local RDF export test (without   DB dependency) [r7677](https://sourceforge.net/p/ambit/code/7687) . The class is [TestSubstanceRDFExport.java](https://svn.code.sf.net/p/ambit/code/trunk/ambit2-all/ambit2-rest/src/test/java/ambit2/rest/substance/TestSubstanceRDFExport.java)
- Added RDF serialisation for composition (needs improvements) [r7690](http://sourceforge.net/p/ambit/code/7690)
- [r7694](https://sourceforge.net/p/ambit/code/7694/) deployed at [enmtest](https://apps.ideaconsult.net/enmtest/bundle/1/substance?media=application%2Frdf%2Bxml),  with latest commits by @egonw

**Comment by vedina** [comment]
Closing, RDF is implemented read/write
