### ISSUE TITLE
P-CHEM conditions missing in RDF serialisation of Protein Corona bundle

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#95]
Most P-CHEM properties in the Protein Corona dataset have been measured with and without Human Serum. In the JSON representation I have to retrieve the study in order to find conditions under ["effects"]["conditions"]. I could not find any information about the media in the RDF representation of the Protein Corona dataset (JSON_LD, Turtle).

**Comment by vedina** [comment]
The RDF does have entries for serum

````rdf+xml
  <rdf:Description rdf:about="endpoint/ID509C1">
    <sso:has-value>Human serum (Sigma #H4522)</sso:has-value>
    <rdfs:label>MEDIUM</rdfs:label>
  </rdf:Description>
````
