### ISSUE TITLE
MODENA EC50/25 measurement groups

### ISSUE THREAD

**Issue by ghost** [enanomapper/data.enanomapper.net#97]
I am trying to find out if there are sufficient examples for modelling one of the EC50/25 endpoints in the MODENA dataset. The JSON_LD representations returns entries like

````json
`{"@id"=>"ep:ID16863", "@type"=>"bao:BAO_0000179", "standardisedUnit"=>"opsUnit:MicrogramPerMilliliter", "IAO_0000136"=>"substance:XLSX-adf890e9-3623-3a0e-b601-11f8e5e2f3cb", "has-unit"=>"ug/ml", "sio:has-value"=>2076.8564466795024, "label"=>"EC50"}`
````

From this entry it is unclear if the EC50 value was obtained by the Cell viability, LDH release, ATP or MTT assay.

The ep:ID16863 "@id"  seems to belong to the following measurement group:

````json
`{"@id"=>"mgroup:XLSX-f5ba28f1-d236-415d-af07-6ffe7b15585e", "@type"=>"bao:BAO_0000040", "OBI_0000299"=>["ep:ID16864", "ep:ID16863", "ep:ID16862"]}`
````

But `curl -H 'Accept:application/ld+json' https://data.enanomapper.net/measuregroup:XLSX-41595fe0-3c7b-4725-b209-f0267aa83da7` returns (sorry I cannot figure out how to escape html strings here):

````html
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<h3>The method specified in the request is not allowed for the resource identified by the request URI</h3><p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>
````

How can I find the assay corresponding to this data entry?
BTW: I have the same problem with JSON studies.

**Comment by vedina** [comment]
there is no /measuregroup resource, hence the returned error is correct

**Comment by vedina** [comment]
The plain json clearly specifies the study parameters

see the html
https://data.enanomapper.net/substance/XLSX-adf890e9-3623-3a0e-b601-11f8e5e2f3cb/study

The [JSON](
https://data.enanomapper.net/substance/XLSX-adf890e9-3623-3a0e-b601-11f8e5e2f3cb/study?media=application/json) structure is shown below (the same entry as for the RDF in next post)

![image](https://cloud.githubusercontent.com/assets/211190/21154895/bc4dcb76-c178-11e6-8f36-5cdbba8c23c5.png)

**Comment by vedina** [comment]
The RDF data model should be able to represent all info about the study, without additional queries.

Example below with N3 - it does link LDH with the EC50 entry.  `NPO_1709` is the term for the LDH assay. The assay `XLSX-41595fe0-3c7b-4725-b209-f0267aa83da7` is of type `NPO_1709` and has the measure group `mgroup:XLSX-41595fe0-3c7b-4725-b209-f0267aa83da7`. 

The same links should exist with all RDF serializations

https://data.enanomapper.net/substance/XLSX-adf890e9-3623-3a0e-b601-11f8e5e2f3cb?media=text/n3

````
ref:E086C4B4  dc:publisher  owner:MODENA ;
        dc:title      "015" .

ap:076C0843  a    obo:OBI_0000272 ;
        dc:title  "LDH" 

as:XLSX-41595fe0-3c7b-4725-b209-f0267aa83da7
        a                npo:NPO_1709 , bao:BAO_0000015 ;
        dc:title         "015" ;
        dcterms:source   ref:E086C4B4 ;
        bao:BAO_0000209  mgroup:XLSX-41595fe0-3c7b-4725-b209-f0267aa83da7 ;
        bao:BAO_0002846  ap:076C0843 .

mgroup:XLSX-41595fe0-3c7b-4725-b209-f0267aa83da7
        a                bao:BAO_0000040 ;
        obo:OBI_0000299  ep:ID16867 , ep:ID16866 , ep:ID16865 .

ep:ID16866  a                 bao:BAO_0000179 ;
        rdfs:label            "EC50" ;
        ops:standardisedUnit  opsUnit:MicrogramPerMilliliter ;
        obo:IAO_0000136       substance:XLSX-adf890e9-3623-3a0e-b601-11f8e5e2f3cb ;
        sio:has-unit          "ug/ml" ;
        sio:has-value         "113.05101991460714"^^xsd:double .

````

@egonw may explain more about the RDF representation

**Comment by ghost** [comment]
Thanks, I can find LDH, ATP and MTT assays (I think I did not check before filing the issue)! But I was primarily interested in Cell viablility, does it have a different name?

**Comment by ghost** [comment]
Just for my understanding: Whats the purpose of measurement groups (mgroup)?

**Comment by vedina** [comment]
yes, there is an ontology term for cell viability, but cell viability is an endpoint, measured by any of these three assays

**Comment by vedina** [comment]
The measure group is one of the concepts of the BAO data model, which is used by the RDF serialisaiton for substances and studies here.   This [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/pmid/25093074/) describes the BAO data model .  There is nice illustration , including `measure group` 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4108877/figure/F5/

(very roughly speaking it's a way to represent one assay may measure more than one value)
You may notice the picture shows hierarchical organisation of measure groups, we are not supporting this yet, but will in very near future.

**Comment by ghost** [comment]
Thanks for clarification!
